/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
const tracks = [
  {
    id: 1,
    name: "Mario Kart Stadium",
    img: "MK8-_Mario_Kart_Stadium.png",
    prix_id: 1,
  },
  { id: 2, name: "Water Park", img: "MK8-_Water_Park.png", prix_id: 1 },
  {
    id: 3,
    name: "Sweet Sweet Canyon",
    img: "MK8-_Sweet_Sweet_Canyon.png",
    prix_id: 1,
  },
  {
    id: 4,
    name: "Thwomp Ruins",
    img: "MK8-_Thwomp_Ruins.png",
    prix_id: 1,
  },
  {
    id: 5,
    name: "Mario Circuit",
    img: "MK8-_Mario_Circuit.png",
    prix_id: 2,
  },
  {
    id: 6,
    name: "Toad Harbor",
    img: "MK8-_Toad_Harbor.png",
    prix_id: 2,
  },
  {
    id: 7,
    name: "Twisted Mansion",
    img: "MK8-_Twisted_Mansion.png",
    prix_id: 2,
  },
  {
    id: 8,
    name: "Shy Guy Falls",
    img: "MK8-_Shy_Guy_Falls.png",
    prix_id: 2,
  },
  {
    id: 9,
    name: "Sunshine Airport",
    img: "MK8-_Sunshine_Airport.png",
    prix_id: 3,
  },
  {
    id: 10,
    name: "Dolphin Shoals",
    img: "MK8-_Dolphin_Shoals.png",
    prix_id: 3,
  },
  {
    id: 11,
    name: "Electrodrome",
    img: "MK8-_Electrodrome.png",
    prix_id: 3,
  },
  {
    id: 12,
    name: "Mount Wario",
    img: "MK8-_Mount_Wario.png",
    prix_id: 3,
  },
  {
    id: 13,
    name: "Cloudtop Cruise",
    img: "MK8-_Cloudtop_Cruise.png",
    prix_id: 4,
  },
  {
    id: 14,
    name: "Bone-Dry Dunes",
    img: "MK8-_Bone-Dry_Dunes.png",
    prix_id: 4,
  },
  {
    id: 15,
    name: "Bowser's Castle",
    img: "MK8-_Bowsers_Castle.png",
    prix_id: 4,
  },
  {
    id: 16,
    name: "Rainbow Road",
    img: "MK8-_Rainbow_Road.png",
    prix_id: 4,
  },
  {
    id: 17,
    name: "GCN Yoshi Circuit",
    img: "MK8-_GCN_Yoshi_Circuit.png",
    prix_id: 5,
  },
  {
    id: 18,
    name: "Excitebike Arena",
    img: "MK8-DLC-Course-icon-ExcitebikeArena.png",
    prix_id: 5,
  },
  {
    id: 19,
    name: "Dragon Driftway",
    img: "MK8-DLC-Course-icon-DragonDriftway.png",
    prix_id: 5,
  },
  {
    id: 20,
    name: "Mute City",
    img: "MK8-DLC-Course-icon-MuteCity.png",
    prix_id: 5,
  },
  {
    id: 21,
    name: "GCN Baby Park",
    img: "MK8-DLC-Course-icon-GCN_BabyPark.png",
    prix_id: 6,
  },
  {
    id: 22,
    name: "GBA Cheese Land",
    img: "MK8-DLC-Course-icon-GBA_CheeseLand.png",
    prix_id: 6,
  },
  {
    id: 23,
    name: "Wild Woods",
    img: "MK8-DLC-Course-icon-WildWoods.png",
    prix_id: 6,
  },
  {
    id: 24,
    name: "Animal Crossing",
    img: "MK8-DLC-Course-icon-AnimalCrossing.png",
    prix_id: 6,
  },
  {
    id: 25,
    name: "Wii Moo Moo Meadows",
    img: "MK8-_Wii_Moo_Moo_Meadows.png",
    prix_id: 7,
  },
  {
    id: 26,
    name: "GBA Mario Circuit",
    img: "MK8-_GBA_Mario_Circuit.png",
    prix_id: 7,
  },
  {
    id: 27,
    name: "DS Cheep Cheep Beach",
    img: "MK8-_DS_Cheep_Cheep_Beach.png",
    prix_id: 7,
  },
  {
    id: 28,
    name: "N64 Toad's Turnpike",
    img: "MK8-_N64_Toads_Turnpike.png",
    prix_id: 7,
  },
  {
    id: 29,
    name: "GCN Dry Dry Desert",
    img: "MK8-_GCN_Dry_Dry_Desert.png",
    prix_id: 8,
  },
  {
    id: 30,
    name: "SNES Donut Plains 3",
    img: "MK8-_SNES_Donut_Plains_3.png",
    prix_id: 8,
  },
  {
    id: 31,
    name: "N64 Royal Raceway",
    img: "MK8-_N64_Royal_Raceway.png",
    prix_id: 8,
  },
  {
    id: 32,
    name: "3DS DK Jungle",
    img: "MK8-_3DS_DK_Jungle.png",
    prix_id: 8,
  },
  {
    id: 33,
    name: "DS Wario Stadium",
    img: "MK8-_DS_Wario_Stadium.png",
    prix_id: 9,
  },
  {
    id: 34,
    name: "GCN Sherbet Land",
    img: "MK8-_GCN_Sherbet_Land.png",
    prix_id: 9,
  },
  {
    id: 35,
    name: "3DS Music Park",
    img: "MK8-_3DS_Music_Park.png",
    prix_id: 9,
  },
  {
    id: 36,
    name: "N64 Yoshi Valley",
    img: "MK8-_N64_Yoshi_Valley.png",
    prix_id: 9,
  },
  {
    id: 37,
    name: "Tick-Tock Clock",
    img: "MK8-_Tick_Tock_Clock.png",
    prix_id: 10,
  },
  {
    id: 38,
    name: "3DS Piranha Plant Slide",
    img: "MK8-_3DS_Piranha_Plant_Slide.png",
    prix_id: 10,
  },
  {
    id: 39,
    name: "Wii Grumble Volcano",
    img: "MK8-_Wii_Grumble_Volcano.png",
    prix_id: 10,
  },
  {
    id: 40,
    name: "N64 Rainbow Road",
    img: "MK8-_N64_Rainbow_Road.png",
    prix_id: 10,
  },
  {
    id: 41,
    name: "Wii Wario's Gold Mine",
    img: "MK8-DLC-Course-icon-Wii_WariosGoldMine.png",
    prix_id: 11,
  },
  {
    id: 42,
    name: "SNES Rainbow Road",
    img: "MK8-DLC-Course-icon-SNES_RainbowRoad.png",
    prix_id: 11,
  },
  {
    id: 43,
    name: "Ice Ice Outpost",
    img: "MK8-DLC-Course-icon-IceIceOutpost.png",
    prix_id: 11,
  },
  {
    id: 44,
    name: "Hyrule Circuit",
    img: "MK8-DLC-Course-icon-HyruleCircuit.png",
    prix_id: 11,
  },
  {
    id: 45,
    name: "3DS Neo Bowser City",
    img: "MK8-DLC-Course-icon-3DS_NeoBowserCity.png",
    prix_id: 12,
  },
  {
    id: 46,
    name: "GBA Ribbon Road",
    img: "MK8-DLC-Course-icon-GBA_RibbonRoad.png",
    prix_id: 12,
  },
  {
    id: 47,
    name: "Super Bell Subway",
    img: "MK8-DLC-Course-icon-SuperBellSubway.png",
    prix_id: 12,
  },
  {
    id: 48,
    name: "Big Blue",
    img: "MK8-DLC-Course-icon-BigBlue.png",
    prix_id: 12,
  },
  {
    id: 49,
    name: "Tour Paris Promenade",
    img: "152px-MK8D_Tour_Paris_Promenade_Course_Icon.png",
    prix_id: 13,
  },
  {
    id: 50,
    name: "3DS Toad Circuit",
    img: "152px-MK8D_3DS_Toad_Circuit_Course_Icon.png",
    prix_id: 13,
  },
  {
    id: 51,
    name: "N64 Choco Mountain",
    img: "152px-MK8D_N64_Choco_Mountain_Course_Icon.png",
    prix_id: 13,
  },
  {
    id: 52,
    name: "Wii Coconut Mall",
    img: "152px-MK8D_Wii_Coconut_Mall_Course_Icon.png",
    prix_id: 13,
  },
  {
    id: 53,
    name: "Tour Tokyo Blur",
    img: "152px-MK8D_Tour_Tokyo_Blur_Course_Icon.png",
    prix_id: 14,
  },
  {
    id: 54,
    name: "DS Shroom Ridge",
    img: "152px-MK8D_DS_Shroom_Ridge_Course_Icon.png",
    prix_id: 14,
  },
  {
    id: 55,
    name: "GBA Sky Garden",
    img: "152px-MK8D_GBA_Sky_Garden_Course_Icon.png",
    prix_id: 14,
  },
  {
    id: 56,
    name: "Ninja Hideaway",
    img: "152px-MK8D_Ninja_Hideaway_Course_Icon.png",
    prix_id: 14,
  },
  {
    id: 57,
    name: "Tour New York Minute",
    img: "152px-MK8D_Tour_New_York_Minute_Course_Icon.png",
    prix_id: 15,
  },
  {
    id: 58,
    name: "SNES Mario Circuit 3",
    img: "152px-MK8D_SNES_Mario_Circuit_3_Course_Icon.png",
    prix_id: 15,
  },
  {
    id: 59,
    name: "N64 Kalimari Desert",
    img: "152px-MK8D_N64_Kalimari_Desert_Course_Icon.png",
    prix_id: 15,
  },
  {
    id: 60,
    name: "DS Waluigi Pinball",
    img: "152px-MK8D_DS_Waluigi_Pinball_Course_Icon.png",
    prix_id: 15,
  },
  {
    id: 61,
    name: "Tour Sydney Sprint",
    img: "152px-MK8D_Tour_Sydney_Sprint_Course_Icon.png",
    prix_id: 16,
  },
  {
    id: 62,
    name: "GBA Snow Land",
    img: "152px-MK8D_GBA_Snow_Land_Course_Icon.png",
    prix_id: 16,
  },
  {
    id: 63,
    name: "Wii Mushroom Gorge",
    img: "152px-MK8D_Wii_Mushroom_Gorge_Course_Icon.png",
    prix_id: 16,
  },
  {
    id: 64,
    name: "Sky-High Sundae",
    img: "152px-MK8D_Sky-High_Sundae_Course_Icon.png",
    prix_id: 16,
  },
  {
    id: 65,
    name: "Tour London Loop",
    img: "152px-MK8D_Tour_London_Loop_Course_Icon.png",
    prix_id: 17,
  },
  {
    id: 66,
    name: "Wii Maple Treeway",
    img: "152px-MK8D_Wii_Maple_Treeway_Course_Icon.png",
    prix_id: 17,
  },
  {
    id: 67,
    name: "GBA Boo Lake",
    img: "152px-MK8D_GBA_Boo_Lake_Course_Icon.png",
    prix_id: 17,
  },
  {
    id: 68,
    name: "3DS Rock Rock Mountain",
    img: "152px-MK8D_3DS_Rock_Rock_Mountain_Course_Icon.png",
    prix_id: 17,
  },
  {
    id: 69,
    name: "Tour Berlin Byways",
    img: "152px-MK8D_Tour_Berlin_Byways_Course_Icon.png",
    prix_id: 18,
  },
  {
    id: 70,
    name: "DS Peach Gardens",
    img: "152px-MK8D_DS_Peach_Gardens_Course_Icon.png",
    prix_id: 18,
  },
  {
    id: 71,
    name: "Merry Mountain",
    img: "152px-MK8D_Merry_Mountain_Course_Icon.png",
    prix_id: 18,
  },
  {
    id: 72,
    name: "3DS Rainbow Road",
    img: "152px-MK8D_3DS_Rainbow_Road_Course_Icon.png",
    prix_id: 18,
  },
  {
    id: 73,
    name: "Tour Amsterdam Drift",
    img: "152px-MK8D_Tour_Amsterdam_Drift_Course_Icon.png",
    prix_id: 19,
  },
  {
    id: 74,
    name: "GBA Riverside Park",
    img: "152px-MK8D_GBA_Riverside_Park_Course_Icon.png",
    prix_id: 19,
  },
  {
    id: 75,
    name: "Wii DK Summit",
    img: "152px-MK8D_Wii_DK_Summit_Course_Icon.png",
    prix_id: 19,
  },
  {
    id: 76,
    name: "Yoshi's Island",
    img: "152px-MK8D_Yoshi's_Island_Course_Icon.png",
    prix_id: 19,
  },
  {
    id: 77,
    name: "Tour Bangkok Rush",
    img: "152px-MK8D_Tour_Bangkok_Rush_Course_Icon.png",
    prix_id: 20,
  },
  {
    id: 78,
    name: "DS Mario Circuit",
    img: "MK8-_DS_Mario_Circuit.png",
    prix_id: 20,
  },
  {
    id: 79,
    name: "GCN Waluigi Stadium",
    img: "152px-MK8D_GCN_Waluigi_Stadium_Course_Icon.png",
    prix_id: 20,
  },
  {
    id: 80,
    name: "Tour Singapore Speedway",
    img: "152px-MK8D_Tour_Singapore_Speedway_Course_Icon.png",
    prix_id: 20,
  },
  {
    id: 81,
    name: "Tour Athens Dash",
    img: "152px-MK8D_Tour_Athens_Dash_Course_Icon.png",
    prix_id: 21,
  },
  {
    id: 82,
    name: "GCN Daisy Cruiser",
    img: "152px-MK8D_GCN_Daisy_Cruiser_Course_Icon.png",
    prix_id: 21,
  },
  {
    id: 83,
    name: "Wii Moonview Highway",
    img: "152px-MK8D_Wii_Moonview_Highway_Course_Icon.png",
    prix_id: 21,
  },
  {
    id: 84,
    name: "Squeaky Clean Sprint",
    img: "152px-MK8D_Squeaky_Clean_Sprint_Course_Icon.png",
    prix_id: 21,
  },
  {
    id: 85,
    name: "Tour Los Angeles Laps",
    img: "152px-MK8D_Tour_Los_Angeles_Laps_Course_Icon.png",
    prix_id: 22,
  },
  {
    id: 86,
    name: "GBA Sunset Wilds",
    img: "152px-MK8D_GBA_Sunset_Wilds_Course_Icon.png",
    prix_id: 22,
  },
  {
    id: 87,
    name: "Wii Koopa Cape",
    img: "152px-MK8D_Wii_Koopa_Cape_Course_Icon.png",
    prix_id: 22,
  },
  {
    id: 88,
    name: "Tour Vancouver Velocity",
    img: "152px-MK8D_Tour_Vancouver_Velocity_Course_Icon.png",
    prix_id: 22,
  },
  {
    id: 89,
    name: "Tour Rome Avanti",
    img: "152px-MK8D_Tour_Rome_Avanti_Course_Icon.png",
    prix_id: 23,
  },
  {
    id: 90,
    name: "GCN DK Mountain",
    img: "152px-MK8D_GCN_DK_Mountain_Course_Icon.png",
    prix_id: 23,
  },
  {
    id: 91,
    name: "Wii Daisy Circuit",
    img: "152px-MK8D_Wii_Daisy_Circuit_Course_Icon.png",
    prix_id: 23,
  },
  {
    id: 92,
    name: "Piranha Plant Cove",
    img: "152px-MK8D_Piranha_Plant_Cove_Course_Icon.png",
    prix_id: 23,
  },
  {
    id: 93,
    name: "Tour Madrid Drive",
    img: "152px-MK8D_Tour_Madrid_Drive_Course_Icon.png",
    prix_id: 24,
  },
  {
    id: 94,
    name: "3DS Rosalina's Ice World",
    img: "152px-MK8D_3DS_Rosalina's_Ice_World_Course_Icon.png",
    prix_id: 24,
  },
  {
    id: 95,
    name: "SNES Bowser Castle 3",
    img: "152px-MK8D_SNES_Bowser_Castle_3_Course_Icon.png",
    prix_id: 24,
  },
  {
    id: 96,
    name: "Wii Rainbow Road",
    img: "152px-MK8D_Wii_Rainbow_Road_Course_Icon.png",
    prix_id: 24,
  },
];

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("tracks").del();
  await knex("tracks").insert(tracks);
};
